---
dist: trusty
language: node_js
node_js:
  - "node"

notifications:
  email: false

matrix:
  fast_finish: true

env:
  - TEST_RUN="eslint ."
  - TEST_RUN="./tests/test_ocr_service.sh"

before_install:
  - npm install -g eslint eslint-config-google
  - sudo apt-get install tesseract-ocr

install:
  - npm install .

script: "$TEST_RUN"
