---
notifications:
  email: false

jobs:
  include:
    - stage: lint
      script: eslint .
      language: node_js
      node_js:
        - "node"
      install:
        - npm install -g eslint eslint-config-google

    - stage: test app
      language: bash
      services:
        - docker
      script:
        - ./tests/build-containers
        - ./tests/deploy-containers
        - ./tests/test_ocr_service.sh
