apiVersion: v1
kind: Service
metadata:
  name: pubgredzone-ocr
  labels:
    app: ocr
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: ocr
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubgredzone-ocr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - name: pubgredzone-ocr
        image: anthonyamanse/pubgredzone-ocr
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
