---
apiVersion: v1
kind: Pod
metadata:
  name: pubgredzone
spec:
  containers:
    - name: ocr
      image: pubgredzone:ocr
      ports:
        - containerPort: 3001
    - name: app
      image: pubgredzone:app
      ports:
        - containerPort: 3000
